spring:
  application:
    name: demo
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/SB_AM
    username: root
    password: 
  mvc:
    view:
      prefix: /WEB-INF/jsp/
      suffix: .jsp
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
  mail:
    host: smtp.gmail.com
    port: 587
    username: anjaeudv@gmail.com
    password: zbnt yjmv nodx kpvl
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
    
custom:
  file:
    dir: D:cjhupload
#server:
#  port: 8081
#  servlet:
#    context-path: /test



#
#spring.mail.host=smtp.gmail.com
#spring.mail.port=465
#spring.mail.username= 송신자 이메일
#spring.mail.password= 앱 비밀번호
#spring.mail.properties.mail.smtp.auth=true
#spring.mail.protocol=smtps?